version: "3.8"
services:
  cc-tracker:
    build: .
    image: cc-tracker:latest
    container_name: cc-tracker
    ports:
      - "3535:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=changeme
      - FLASK_SECRET=please-change-me
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
      - ALERT_EMAIL=
      - TWILIO_SID=
      - TWILIO_TOKEN=
      - TWILIO_FROM=
      - TIMEZONE=America/Indiana/Indianapolis
    restart: unless-stopped
