import axios from 'axios';
axios.defaults.withCredentials = true;
const API = '/api';
export const login = (user, pass) => axios.post(API+'/login',{user,pass}).then(r=>r.data);
export const register = (user, pass) => axios.post(API+'/register',{user,pass}).then(r=>r.data);
export const logout = () => axios.post(API+'/logout').then(r=>r.data);
export const whoami = () => axios.get(API+'/whoami').then(r=>r.data);
export const getCards = () => axios.get(API+'/cards').then(r=>r.data);
export const addCard = (p) => axios.post(API+'/cards', p).then(r=>r.data);
export const updateCard = (id,p) => axios.put(API+'/cards/'+id, p).then(r=>r.data);
export const deleteCard = (id) => axios.delete(API+'/cards/'+id).then(r=>r.data);
export const getStatuses = () => axios.get(API+'/statuses').then(r=>r.data);
export const getHistory = (id) => axios.get(API+'/history/'+id).then(r=>r.data);
export const downloadReport = (month) => window.open(API+'/report?month='+month, '_blank');
export const getSettings = () => axios.get(API+'/settings').then(r=>r.data);
export const putSettings = (data) => axios.put(API+'/settings', data).then(r=>r.data);
export const listUsers = () => axios.get(API+'/users').then(r=>r.data);
export const addUser = (u) => axios.post(API+'/users', u).then(r=>r.data);
export const modifyUser = (id, u) => axios.put(API+'/users/'+id, u).then(r=>r.data);
export const deleteUser = (id) => axios.delete(API+'/users/'+id).then(r=>r.data);
